version: '3.8'

services:
  app:
    build:
      context: .
    container_name: travel_planer
    ports:
      - "8000:8000"
    volumes:
      - .:/t_p
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=1